<br /><br />
<div id="view-content">
	<p>View script for controller <b>Test</b> and script/action name <b>object</b></p>
</div>

<?php
error_reporting(E_ERROR | E_WARNING | E_PARSE | E_NOTICE);

require_once 'Zaboy/Services.php';
$obj1 = new Zaboy_Service();
$obj1copy = $obj1;
$obj2 = new Zaboy_Service();
$obj1ref = & $obj1;
$obj1copyRef = & $obj1copy;
if ($obj1 === $obj1copy) {
        echo 'I am clever';
    }else{
        echo  'I am wrong';
}

echo '<br><br><br>';


$paramArray[] = $obj1;
$param2 = $obj1;

function compare($paramArray, $param2) {
    if ($paramArray === $param2) {
            echo 'equal';
        }else{
            echo  'not equal';
    }    
}
compare($param2,$obj1);

//http://php.net/manual/ru/function.error-reporting.php
function bool2str($bool)
{
    if ($bool === false) {
        return 'FALSE';
    } else {
        return 'TRUE';
    }
}

function compareObjectsByVal($o1, $o2)
{
    echo '<br><br>' . 'compareObjectsByVal';
    echo '<br>o1 == o2 : ' . bool2str($o1 == $o2) . "<br>\n";
    //echo 'o1 != o2 : ' . bool2str($o1 != $o2) . "<br><br>\n";
    echo 'o1 === o2 : ' . bool2str($o1 === $o2) . "<br>\n";
    //echo 'o1 !== o2 : ' . bool2str($o1 !== $o2) . "<br>\n";

}

function compareObjectsByRef(&$o1, &$o2)
{
    echo '<br><br>' . 'compareObjectsByRef';
    echo '<br>o1 == o2 : ' . bool2str($o1 == $o2) . "<br>\n";
    //echo 'o1 != o2 : ' . bool2str($o1 != $o2) . "<br><br>\n";
    echo 'o1 === o2 : ' . bool2str($o1 === $o2) . "<br>\n";
    //echo 'o1 !== o2 : ' . bool2str($o1 !== $o2) . "<br>\n";

}

class Flag
{
    public $flag;

    function Flag($flag = true) {
        $this->flag = $flag;
    }
}

class OtherFlag
{
    public $flag;

    function OtherFlag($flag = true) {
        $this->flag = $flag;
    }
}

$obj1class1 = new Flag();
$obj2class1 = new Flag();
$obj1class1Copy = $obj1class1;
$obj1class2 = new OtherFlag();
$obj1class2->OtherFlag(true);

echo "<br><br>Два экземпляра одного и того же класса\n";

compareObjectsByRef($obj1class1, $obj2class1);
compareObjectsByVal($obj1class1, $obj2class1);

echo "<br>\nДве ссылки на один и тот же экземпляр\n";
compareObjectsByRef($obj1class1, $obj1class1Copy);
compareObjectsByVal($obj1class1, $obj1class1Copy);

echo "<br>\nЭкземпляры двух разных классов\n";
compareObjectsByRef($obj1class1, $obj1class2);
compareObjectsByVal($obj1class1, $obj1class2);



